/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Time = IDL.Int;
export const Contact = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Text,
  'message' : IDL.Text,
  'timestamp' : Time,
});
export const Enquiry = IDL.Record({
  'country' : IDL.Text,
  'contactPerson' : IDL.Text,
  'timestamp' : Time,
  'companyName' : IDL.Text,
  'shippingPreference' : IDL.Text,
  'quantity' : IDL.Text,
  'products' : IDL.Vec(IDL.Text),
});
export const Product = IDL.Record({
  'nutritionalInfo' : IDL.Text,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'sizes' : IDL.Vec(IDL.Text),
  'packaging' : IDL.Text,
});

export const idlService = IDL.Service({
  'addProduct' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Vec(IDL.Text), IDL.Text, IDL.Text],
      [],
      [],
    ),
  'getAllContacts' : IDL.Func([], [IDL.Vec(Contact)], ['query']),
  'getAllEnquiries' : IDL.Func([], [IDL.Vec(Enquiry)], ['query']),
  'getCompanyInfo' : IDL.Func(
      [],
      [
        IDL.Record({
          'brands' : IDL.Vec(IDL.Text),
          'exportMarkets' : IDL.Vec(IDL.Text),
          'name' : IDL.Text,
          'businessType' : IDL.Text,
          'keywords' : IDL.Vec(IDL.Text),
          'location' : IDL.Text,
        }),
      ],
      ['query'],
    ),
  'getProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
  'submitContact' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  'submitEnquiry' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Vec(IDL.Text), IDL.Text, IDL.Text],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Time = IDL.Int;
  const Contact = IDL.Record({
    'name' : IDL.Text,
    'email' : IDL.Text,
    'message' : IDL.Text,
    'timestamp' : Time,
  });
  const Enquiry = IDL.Record({
    'country' : IDL.Text,
    'contactPerson' : IDL.Text,
    'timestamp' : Time,
    'companyName' : IDL.Text,
    'shippingPreference' : IDL.Text,
    'quantity' : IDL.Text,
    'products' : IDL.Vec(IDL.Text),
  });
  const Product = IDL.Record({
    'nutritionalInfo' : IDL.Text,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'sizes' : IDL.Vec(IDL.Text),
    'packaging' : IDL.Text,
  });
  
  return IDL.Service({
    'addProduct' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Vec(IDL.Text), IDL.Text, IDL.Text],
        [],
        [],
      ),
    'getAllContacts' : IDL.Func([], [IDL.Vec(Contact)], ['query']),
    'getAllEnquiries' : IDL.Func([], [IDL.Vec(Enquiry)], ['query']),
    'getCompanyInfo' : IDL.Func(
        [],
        [
          IDL.Record({
            'brands' : IDL.Vec(IDL.Text),
            'exportMarkets' : IDL.Vec(IDL.Text),
            'name' : IDL.Text,
            'businessType' : IDL.Text,
            'keywords' : IDL.Vec(IDL.Text),
            'location' : IDL.Text,
          }),
        ],
        ['query'],
      ),
    'getProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
    'submitContact' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
    'submitEnquiry' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Vec(IDL.Text), IDL.Text, IDL.Text],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };